import {Component,useEffect,useRef,useState} from 'react';
import type {ReactNode} from 'react';
import {ArrowUpRight,ArrowUp,ArrowLeft,Box,ChevronRight,Expand,Layers,Pause,Play,RotateCcw,Server,Compass,Code,Zap} from 'lucide-react';
import Scene from './Scene';
import {byId,journey,type ComponentId} from './graph';
import {focus,ancestry,inBranch} from './exploration';
class SceneBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<div className="webgl-error">3D rendering is unavailable. Enable WebGL and reload to explore.</div>:this.props.children}}
export default function App(){
const [selected,setSelected]=useState<ComponentId>('laptop');const [overview,setOverview]=useState(true);const [exploded,setExploded]=useState(false);const [mode,setMode]=useState<'free'|'follow'>('free');const [step,setStep]=useState(-1);const [running,setRunning]=useState(false);const [progress,setProgress]=useState(0);const [prompt,setPrompt]=useState('Why is the sky blue?');const [sent,setSent]=useState('');const [complete,setComplete]=useState(false);const [reset,setReset]=useState(0);const [detail,setDetail]=useState(false);const [responseCount,setResponseCount]=useState(0);const elapsed=useRef(0);
const node=byId[selected];const path=ancestry(selected);const children=focus[selected].parts;const siblings=focus[focus[selected].parent??selected].parts;
const response=/sky.*blue/i.test(sent)?'Air molecules scatter shorter blue wavelengths of sunlight more strongly than longer red wavelengths, making the daytime sky appear blue.':'Accelerators processed your prompt using model weights and memory, supported by electricity and cooling. The output returned to your device.';
const select=(id:ComponentId)=>{setRunning(false);setSelected(id);setOverview(false);setReset(r=>r+1);setDetail(false);if(inBranch(id,'server'))setExploded(true)};
const showAll=()=>{setRunning(false);setOverview(true);setReset(r=>r+1);setDetail(false)};
const back=()=>{const parent=focus[selected].parent;parent?select(parent):showAll()};
const applyStep=(i:number)=>{setOverview(false);const s=journey[i];setSelected(s.node);setStep(i);setExploded(inBranch(s.node,'server'));setProgress(0);elapsed.current=0};
const start=()=>{if(!prompt.trim())return;setSent(prompt.trim());setMode('follow');setComplete(false);setResponseCount(0);applyStep(0);setRunning(true)};
useEffect(()=>{if(!running||step<0)return;let last=performance.now();const timer=window.setInterval(()=>{const now=performance.now();elapsed.current+=(now-last)/1000;last=now;const p=elapsed.current/journey[step].duration;setProgress(Math.min(p,1));if(step===journey.length-1)setResponseCount(Math.floor(response.length*Math.min(p*1.15,1)));if(p>=1){if(step<journey.length-1)applyStep(step+1);else{setRunning(false);setComplete(true);setResponseCount(response.length)}}},50);return()=>clearInterval(timer)},[running,step,response]);
const free=()=>{setMode('free');setRunning(false)};
const resume=()=>{if(step<0)return;setSelected(journey[step].node);setRunning(true)};
return <div className="app-shell spatial-app"><header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();free();showAll()}}><span className="brand-symbol"><Box size={23}/></span><span>AI ATLAS<span className="brand-caption">THE PHYSICAL STACK</span></span></a><div className="mode-switch"><button className={mode==='free'?'chosen':''} onClick={free}><Compass size={15}/>Explore</button><button className={mode==='follow'?'chosen':''} onClick={()=>{setMode('follow');if(step<0)start()}}><Play size={14}/>Follow a prompt</button></div><div className="edition">Device · Compute · Software · Energy · Materials</div></header>
<main className="workspace"><section className="world" aria-label="Interactive 3D infrastructure"><div id="world-labels" className="world-labels"/><div className="scene-container"><SceneBoundary><Scene environment={node.environment} selected={selected} select={select} exploded={exploded} running={running} step={step} reset={reset} layer="all" overview={overview}/></SceneBoundary></div>
<div className="scene-heading unified-heading"><nav className="breadcrumbs" aria-label="Breadcrumb">{!overview&&<button title="Go back one level" onClick={back}><ArrowLeft size={15}/></button>}<button onClick={showAll}>All systems</button>{!overview&&path.map(id=><span className="crumb" key={id}><ChevronRight size={11}/><button onClick={()=>select(id)} aria-current={id===selected?'location':undefined}>{byId[id].name}</button></span>)}</nav><div className="eyebrow">{overview?'[ PHYSICAL INFRASTRUCTURE ]':'[ EXPLORE INSIDE ]'}</div><h1>{overview?'The physical world of AI.':node.name}</h1><p>{overview?'Click a system to zoom in. Keep exploring its parts.':children.length?'Click a labeled part to look closer. Everything stays in the same world.':'A closer look. Select a neighboring part or step back.'}</p></div>
<div className="scene-tools"><button className="show-all" onClick={showAll}><Layers size={16}/><span>Show all</span></button><button title="Reset view" onClick={()=>setReset(r=>r+1)}><RotateCcw size={16}/></button>{inBranch(selected,'server')&&!overview&&<button className={exploded?'tool-active':''} title={exploded?'Collapse components':'Explode components'} onClick={()=>setExploded(v=>!v)}><Expand size={16}/></button>}</div>
{!overview&&<div className="parts-rail" aria-label="Parts in this system"><span className="section-label">{children.length?'PARTS IN THIS SYSTEM':'NEARBY PARTS'}</span>{(children.length?children:siblings).map(id=><button key={id} className={id===selected?'active':''} onClick={()=>select(id)}>{byId[id].name}<ArrowUpRight size={12}/></button>)}</div>}
{!overview&&mode==='free'&&<div className="spatial-caption"><div><span className="eyebrow">{node.category}</span><p>{node.summary}</p>{node.makers&&<p className="makers"><strong>Who makes it:</strong> {node.makers}</p>}{detail&&<><p className="technical-text">{node.technical}</p>{node.source&&<a href={node.source} target="_blank" rel="noreferrer">Read the source ↗</a>}</>}</div><button onClick={()=>setDetail(v=>!v)} aria-expanded={detail}>{detail?'Less detail':'More detail'}</button></div>}
<div className="scene-bottom"><div className="scene-key"><span><i className="key-data"/>Data</span><span><i className="key-power"/>Power</span><span><i className="key-cooling"/>Cooling</span></div><div className="gesture-hint">Drag to orbit · Scroll to zoom · Right-drag to pan</div></div>
{mode==='follow'&&step>=0&&<div className="journey-panel" aria-live="polite"><div className="journey-top"><span className="eyebrow">{complete?'JOURNEY COMPLETE':`STEP ${step+1} OF ${journey.length}`}</span><span className="simulation">Illustrative timing</span></div><h2>{complete?'Back at your screen':journey[step].title}</h2><p>{journey[step].description}</p><div className="timeline">{journey.map((s,i)=><button key={i} aria-label={`Go to step ${i+1}: ${s.title}`} onClick={()=>{setRunning(false);setComplete(false);applyStep(i)}}><span style={{width:i<step?'100%':i===step?`${progress*100}%`:'0%'}}/></button>)}</div><div className="journey-actions"><button onClick={()=>complete?start():running?setRunning(false):resume()}>{running?<Pause size={15}/>:<Play size={15}/>} {complete?'Replay':running?'Pause & explore':'Resume journey'}</button><button disabled={step>=journey.length-1} onClick={()=>applyStep(step+1)}>Next <ChevronRight size={15}/></button></div>{step===journey.length-1&&<div className="demo-answer"><span>SIMULATED RESPONSE</span><p>{response.slice(0,responseCount)||'Receiving output…'}</p></div>}</div>}
</section></main>
<footer className="command-dock"><div className="prompt-section"><div className="prompt-label"><strong>Follow a prompt through the physical world.</strong></div><form onSubmit={e=>{e.preventDefault();start()}}><label className="sr-only" htmlFor="prompt">Your prompt</label><input id="prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask an AI model anything…" maxLength={500}/><button className="send" disabled={!prompt.trim()} aria-label="Send prompt"><ArrowUp size={19}/></button></form></div><div className="quick-explore"><span className="section-label">EXPLORE INSIDE</span><div><button onClick={()=>{free();select('datacenter')}}><Server size={16}/>Data center<ArrowUpRight size={14}/></button><button onClick={()=>{free();select('server')}}><Box size={16}/>GPU server<ArrowUpRight size={14}/></button><button onClick={()=>{free();select('software')}}><Code size={16}/>Software<ArrowUpRight size={14}/></button><button onClick={()=>{free();select('energy')}}><Zap size={16}/>Energy<ArrowUpRight size={14}/></button></div></div></footer><div className="footnote"><span>Schematic · Equipment shown at different scales</span><span>Educational simulation · No prompt is sent to an AI service</span></div></div>}
